# SPDX-License-Identifier: MIT
---
- name: Call insights status
  shell: insights-client --status & wait
  changed_when: false
  register: __rhc_insights_status
  failed_when: __rhc_insights_status.rc not in [0,1]
